import { z } from 'zod';

const environmentSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  HOST: z.string().default('127.0.0.1'),
  DATABASE_URL: z.string().url().optional(),
  // Split RDS credentials (as injected separately by ECS/Secrets Manager, which can't compose
  // a single connection-string secret value). Used to build DATABASE_URL when it isn't set directly.
  PGHOST: z.string().optional(),
  PGPORT: z.coerce.number().int().min(1).max(65535).default(5432),
  PGDATABASE: z.string().default('openmic'),
  PGUSER: z.string().optional(),
  PGPASSWORD: z.string().optional(),
  SIMULATED_AUTH_MODE: z.preprocess((value) => value === 'true' || value === true, z.boolean()).default(false),
  EMAIL_ADAPTER: z.enum(['ses', 'console', 'memory']).optional(),
  EMAIL_QUEUE_URL: z.string().optional(),
  EMAIL_SENDER_ADDRESS: z.string().default('noreply@openmics.org'),
  AWS_REGION: z.string().default('eu-west-1'),
  COGNITO_USER_POOL_ID: z.string().optional(),
  COGNITO_CLIENT_ID: z.string().optional(),
  APP_BASE_URL: z.string().default('http://localhost:5173'),
  LOCATIONIQ_API_KEY: z.string().default(''),
  LOCATIONIQ_BASE_URL: z.string().default('https://us1.locationiq.com'),
  // Signs the short-lived, single-purpose roster SSE stream token (see decisions.md → Live
  // updates). The insecure default is fine for local/dev/test; production must override it.
  STREAM_TOKEN_SECRET: z.string().default('dev-insecure-stream-token-secret-change-me'),
  // Media pipeline (decisions.md → "Media delivery"). Defaults keep local dev and tests
  // fully offline: the local storage adapter never touches AWS.
  MEDIA_STORAGE_ADAPTER: z.enum(['s3', 'local']).optional(),
  MEDIA_BUCKET: z.string().optional(),
  MEDIA_CDN_BASE_URL: z.string().optional(),
  MEDIA_RENDITIONS_QUEUE_URL: z.string().optional(),
  MEDIA_PRESIGN_EXPIRY_SECONDS: z.coerce.number().int().min(60).max(3600).default(900),
  // Shared with the rendition Lambda (infra/lib/lambda/media-renditions), which HMAC-signs
  // its renditions-complete callback with it. The insecure default is fine for local
  // dev/test; production injects the Secrets Manager value generated by MediaStack.
  MEDIA_RENDITIONS_CALLBACK_SECRET: z.string().default('dev-insecure-media-renditions-callback-secret-change-me'),
  // Baked into the API image by apps/api/Dockerfile for OG injection on /media/:id; the
  // placeholder SPA shell is used when the file is absent (local dev without a web build).
  SPA_INDEX_HTML: z.string().default('/app/public/index.html'),
});

export type AppConfig = {
  databaseUrl: string;
  host: string;
  port: number;
  environment: 'development' | 'test' | 'production';
  simulatedAuthMode: boolean;
  emailAdapter: 'ses' | 'console' | 'memory';
  emailQueueUrl?: string;
  emailSenderAddress: string;
  awsRegion: string;
  cognitoUserPoolId?: string;
  cognitoClientId?: string;
  appBaseUrl: string;
  locationIqApiKey: string;
  locationIqBaseUrl: string;
  streamTokenSecret: string;
  mediaStorageAdapter: 's3' | 'local';
  mediaBucket?: string;
  mediaCdnBaseUrl: string;
  mediaRenditionsQueueUrl?: string;
  mediaPresignExpirySeconds: number;
  mediaRenditionsCallbackSecret?: string;
  spaIndexHtmlPath: string;
};

function resolveDatabaseUrl(parsed: z.infer<typeof environmentSchema>): string {
  if (parsed.DATABASE_URL) {
    return parsed.DATABASE_URL;
  }
  if (parsed.PGHOST && parsed.PGUSER && parsed.PGPASSWORD) {
    const credentials = `${encodeURIComponent(parsed.PGUSER)}:${encodeURIComponent(parsed.PGPASSWORD)}`;
    // RDS rejects unencrypted connections; sslmode=no-verify encrypts without needing the
    // RDS CA bundle mounted (Node's default trust store doesn't include it).
    return `postgres://${credentials}@${parsed.PGHOST}:${parsed.PGPORT}/${parsed.PGDATABASE}?sslmode=no-verify`;
  }
  return 'postgres://openmic:openmic_local@127.0.0.1:5432/openmic_dev';
}

export function loadConfig(environment: NodeJS.ProcessEnv = process.env): AppConfig {
  const parsed = environmentSchema.parse(environment);
  const defaultEmailAdapter = parsed.NODE_ENV === 'production' ? 'ses' : parsed.NODE_ENV === 'test' ? 'memory' : 'console';

  return {
    databaseUrl: resolveDatabaseUrl(parsed),
    environment: parsed.NODE_ENV,
    host: parsed.HOST,
    port: parsed.PORT,
    simulatedAuthMode: parsed.SIMULATED_AUTH_MODE,
    emailAdapter: parsed.EMAIL_ADAPTER ?? defaultEmailAdapter,
    emailQueueUrl: parsed.EMAIL_QUEUE_URL,
    emailSenderAddress: parsed.EMAIL_SENDER_ADDRESS,
    awsRegion: parsed.AWS_REGION,
    cognitoUserPoolId: parsed.COGNITO_USER_POOL_ID,
    cognitoClientId: parsed.COGNITO_CLIENT_ID,
    appBaseUrl: parsed.APP_BASE_URL,
    locationIqApiKey: parsed.LOCATIONIQ_API_KEY,
    locationIqBaseUrl: parsed.LOCATIONIQ_BASE_URL,
    streamTokenSecret: parsed.STREAM_TOKEN_SECRET,
    mediaStorageAdapter: parsed.MEDIA_STORAGE_ADAPTER ?? (parsed.NODE_ENV === 'production' ? 's3' : 'local'),
    mediaBucket: parsed.MEDIA_BUCKET,
    mediaCdnBaseUrl: parsed.MEDIA_CDN_BASE_URL ?? 'https://media.test',
    mediaRenditionsQueueUrl: parsed.MEDIA_RENDITIONS_QUEUE_URL,
    mediaPresignExpirySeconds: parsed.MEDIA_PRESIGN_EXPIRY_SECONDS,
    mediaRenditionsCallbackSecret: parsed.MEDIA_RENDITIONS_CALLBACK_SECRET,
    spaIndexHtmlPath: parsed.SPA_INDEX_HTML,
  };
}